name: jobs-manager

services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: jobshunter
      POSTGRES_PASSWORD: jobshunterpassword
      POSTGRES_DB: jobshunter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
